name: Publish

on:
  push:
    tags:
    - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '18.x'
        registry-url: 'https://npm.pkg.github.com'
    - uses: pnpm/action-setup@v2
    - name: Install
      run: pnpm install
    - name: Publish
      run: cd packages/floating-vue && npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
